/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import battle.Battle;
import enemy.Enemy;
import player.Player;

/**
 *
 * @author Owner
 */
public class BattlePanel extends javax.swing.JPanel {

    /**
     * Creates new form BattlePanel
     */
    public BattlePanel() {
        initComponents();
    }
    
    // Instantiation
    public static BattlePanel battlePanel = new BattlePanel();
    Battle battle = new Battle();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        battleText = new javax.swing.JTextArea();
        attackOne = new javax.swing.JButton();
        attackTwo = new javax.swing.JButton();
        attackThree = new javax.swing.JButton();
        attackFour = new javax.swing.JButton();
        attackFive = new javax.swing.JButton();
        attackSix = new javax.swing.JButton();
        fleeButton = new javax.swing.JButton();

        setName("battlePanel");
        setPreferredSize(new java.awt.Dimension(470, 300));

        battleText.setColumns(20);
        battleText.setEditable(false);
        battleText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        battleText.setRows(5);
        jScrollPane1.setViewportView(battleText);

        attackOne.setText("Attack 1");
        attackOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackOneActionPerformed(evt);
            }
        });

        attackTwo.setText("Attack 2");

        attackThree.setText("Attack 3");

        attackFour.setText("Attack 4");

        attackFive.setText("Attack 5");

        attackSix.setText("Attack 6");

        fleeButton.setText("Flee");
        fleeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attackOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attackTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attackThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attackFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attackFive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attackSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fleeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(attackOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attackTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attackThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attackFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attackFive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attackSix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(fleeButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("battlePanel");
    }// </editor-fold>//GEN-END:initComponents

    private void fleeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleeButtonActionPerformed
        gui.MainMenu.setMainMenuPanel(gui.MenuPanel.menuPanel);
    }//GEN-LAST:event_fleeButtonActionPerformed

    private void attackOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackOneActionPerformed
        gui.MenuPanel.enemy.setHealth(10);
        battle.Battle(gui.MenuPanel.player, gui.MenuPanel.enemy);
    }//GEN-LAST:event_attackOneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackFive;
    private javax.swing.JButton attackFour;
    private javax.swing.JButton attackOne;
    private javax.swing.JButton attackSix;
    private javax.swing.JButton attackThree;
    private javax.swing.JButton attackTwo;
    public static javax.swing.JTextArea battleText;
    private javax.swing.JButton fleeButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
